name: bookbyte_user
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  flutter_map: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.4
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/